version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - rust

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:15"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - ci

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "04:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - docker
